<a href="https://colab.research.google.com/github/Sachinsachin21/Transformers/blob/main/Pegasus_txt_summary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install transformers tensorflow

In [2]:
import tensorflow as tf
import pandas as pd
from transformers import PegasusTokenizer, TFPegasusForConditionalGeneration

In [3]:
model_name = "google/pegasus-xsum"

In [4]:
tokenizer = PegasusTokenizer.from_pretrained(model_name)
model = TFPegasusForConditionalGeneration.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/87.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/1.91M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.52M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.39k [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/2.28G [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFPegasusForConditionalGeneration.

Some layers of TFPegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-xsum and are newly initialized: ['final_logits_bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


generation_config.json:   0%|          | 0.00/259 [00:00<?, ?B/s]

In [19]:
ip_txt = input("Enter the text to summarize: ")
print(ip_txt)

Enter the text to summarize: PM Modi on Sunday inaugurated an integrated Bharat Petroleum (BPCL) refinery expansion complex in Kerala's Kochi and dedicated the ₹16,504-crore investment to the nation. The complex would transform Kochi Refinery as the largest state-run refinery in the country, he said. He also laid the foundation stone for a petrochemical complex at the refinery and a skill development institute at Ettumanoor.
PM Modi on Sunday inaugurated an integrated Bharat Petroleum (BPCL) refinery expansion complex in Kerala's Kochi and dedicated the ₹16,504-crore investment to the nation. The complex would transform Kochi Refinery as the largest state-run refinery in the country, he said. He also laid the foundation stone for a petrochemical complex at the refinery and a skill development institute at Ettumanoor.


In [20]:
inputs = tokenizer(ip_txt, return_tensors="tf", padding=True, truncation=True, max_length=512)
inputs

{'input_ids': <tf.Tensor: shape=(1, 82), dtype=int32, numpy=
array([[ 3031, 14349,   124,  1342, 30867,   142,  2833, 24213, 19113,
          143,   788, 68173,   158, 32089,  3847,  1482,   115, 14744,
          131,   116, 47891,   111,  1548,   109,   110,   105,  5357,
          108, 63962,   121, 19971,   216,  1237,   112,   109,  2270,
          107,   139,  1482,   192,  4780, 47891, 56511,   130,   109,
         1368,   449,   121,  5486, 32089,   115,   109,   531,   108,
          178,   243,   107,   285,   163,  4497,   109,  2800,  1909,
          118,   114, 34910,  1482,   134,   109, 32089,   111,   114,
         3016,   486, 12189,   134, 17352, 19431,  8441,   490,   107,
            1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 82), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [21]:
summary_ids = model.generate(inputs['input_ids'], num_beams=4, max_length=150, early_stopping=True)
summary_ids

<tf.Tensor: shape=(1, 28), dtype=int32, numpy=
array([[    0,  4230,  2965, 29839, 14349,   148,  4497,   109,  2800,
         1909,   118,   114, 34910,  1482,   115,   109,  4576,  2128,
          517,   113, 47891,   107,     1,     0,     0,     0,     0,
            0]], dtype=int32)>

In [22]:
summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
print(summary)

Prime Minister Narendra Modi has laid the foundation stone for a petrochemical complex in the southern Indian city of Kochi.
